In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#Read Dataset  and set col index
#created one column (Sl No) in excel file to set up as index column
data=pd.read_excel('C:\\Users\\HP\\Desktop\\iris.xls',index_col=0)
print(data.head())
print(data.shape)
print(data.columns)


       SL   SW   PL   PW Classification
SlNo                                   
1     5.1  3.5  1.4  0.2    Iris-setosa
2     4.9  3.0  1.4  0.2    Iris-setosa
3     NaN  3.2  1.3  0.2    Iris-setosa
4     4.6  3.1  1.5  0.2    Iris-setosa
5     5.0  3.6  1.4  0.2    Iris-setosa
(150, 5)
Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')


In [6]:
#Checking null values in columns
data.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [7]:
print(data.columns)
#Filling null values with mean values of corresponding colmun values
data['SL'].fillna((data['SL'].mean()), inplace=True)
data['SW'].fillna((data['SW'].mean()), inplace=True)
data['PL'].fillna((data['PL'].mean()), inplace=True)
data['PW'].fillna((data['PW'].mean()), inplace=True)

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')


In [8]:
print(data)
print(data.info())
## Do Label Encoding for classification column since it has three values to convert in to numeric
from sklearn.preprocessing import LabelEncoder
label_en=LabelEncoder()
a=['Classification']
for i in np.arange(len(a)):
    data[a[i]]=label_en.fit_transform(data[a[i]])

print(data)

            SL   SW       PL   PW  Classification
SlNo                                             
1     5.100000  3.5  1.40000  0.2     Iris-setosa
2     4.900000  3.0  1.40000  0.2     Iris-setosa
3     5.855944  3.2  1.30000  0.2     Iris-setosa
4     4.600000  3.1  1.50000  0.2     Iris-setosa
5     5.000000  3.6  1.40000  0.2     Iris-setosa
...        ...  ...      ...  ...             ...
146   6.700000  3.0  5.20000  2.3  Iris-virginica
147   6.300000  2.5  5.00000  1.9  Iris-virginica
148   6.500000  3.0  3.75625  2.0  Iris-virginica
149   6.200000  3.4  5.40000  2.3  Iris-virginica
150   5.900000  3.0  5.10000  1.8  Iris-virginica

[150 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float

In [9]:
# Merging Sepal width and height into sepal and Petal respectively  and create two columns 
data['Sepal']=data['SL']+data['SW']
data['Petal']=data['PL']+data['PW']

print(data)

            SL   SW       PL   PW  Classification     Sepal    Petal
SlNo                                                                
1     5.100000  3.5  1.40000  0.2               0  8.600000  1.60000
2     4.900000  3.0  1.40000  0.2               0  7.900000  1.60000
3     5.855944  3.2  1.30000  0.2               0  9.055944  1.50000
4     4.600000  3.1  1.50000  0.2               0  7.700000  1.70000
5     5.000000  3.6  1.40000  0.2               0  8.600000  1.60000
...        ...  ...      ...  ...             ...       ...      ...
146   6.700000  3.0  5.20000  2.3               2  9.700000  7.50000
147   6.300000  2.5  5.00000  1.9               2  8.800000  6.90000
148   6.500000  3.0  3.75625  2.0               2  9.500000  5.75625
149   6.200000  3.4  5.40000  2.3               2  9.600000  7.70000
150   5.900000  3.0  5.10000  1.8               2  8.900000  6.90000

[150 rows x 7 columns]


In [10]:
print(data.columns)
print(data.info())

#Splitting data for testing and training
from sklearn.model_selection import train_test_split
y=data['Classification']
x=data.drop(['Classification'],axis=1)

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2,test_size=.3)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

Index(['SL', 'SW', 'PL', 'PW', 'Classification', 'Sepal', 'Petal'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    int32  
 5   Sepal           150 non-null    float64
 6   Petal           150 non-null    float64
dtypes: float64(6), int32(1)
memory usage: 8.8 KB
None
(105, 6)
(105,)
(45, 6)
(45,)


In [14]:
# thi is a classification problem so use Classifier Algorithm as Random Forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=50,max_depth=500,random_state=42,criterion="entropy")
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import f1_score,confusion_matrix,accuracy_score
#accuracy percentage for prediction

print("Accuracy percentage is",str(round(accuracy_score(y_test,y_pred)*100, 2)))
print(confusion_matrix(y_test,y_pred))
print(rf.feature_importances_)



Accuracy percentage is 97.78
[[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
[0.0959199  0.03360086 0.24636374 0.37026454 0.0105969  0.24325406]


In [15]:
#Implement Logistic Regression 
from sklearn.linear_model import LogisticRegression
logic_model=LogisticRegression()
logic_model.fit(x_train,y_train)
y_pred=logic_model.predict(x_test)
from sklearn.metrics import f1_score,confusion_matrix,accuracy_score
#accuracy percentage for prediction
print("Accuracy percentage is",str(round(accuracy_score(y_test,y_pred)*100, 2)))
print(confusion_matrix(y_test,y_pred))

Accuracy percentage is 95.56
[[16  1  0]
 [ 0 14  1]
 [ 0  0 13]]


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
## Random Forest gives better accuracy in prediction say 97.78 So it can be accepted